create table "AUTHORS" (
    "ID" bigint generated by default as identity primary key,
    "NAME" varchar(255) not null,
    "BIRTH_DATE" date not null
);

create table "BOOKS" (
    "ID" bigint generated by default as identity primary key,
    "TITLE" varchar(255) not null,
    "PRICE" integer not null check ("PRICE" >= 0),
    "PUBLICATION_STATUS" varchar(20) not null
        check ("PUBLICATION_STATUS" in ('UNPUBLISHED', 'PUBLISHED'))
);

create table "BOOK_AUTHORS" (
    "BOOK_ID" bigint not null,
    "AUTHOR_ID" bigint not null,
    primary key ("BOOK_ID", "AUTHOR_ID"),
    constraint "FK_BOOK_AUTHORS_BOOK" foreign key ("BOOK_ID") references "BOOKS"("ID") on delete cascade,
    constraint "FK_BOOK_AUTHORS_AUTHOR" foreign key ("AUTHOR_ID") references "AUTHORS"("ID")
);

create index "IDX_BOOK_AUTHORS_AUTHOR_ID" on "BOOK_AUTHORS"("AUTHOR_ID");
