create table authors (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    birth_date date not null
);

create table books (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    price integer not null check (price >= 0),
    publication_status varchar(20) not null
        check (publication_status in ('UNPUBLISHED', 'PUBLISHED'))
);

create table book_authors (
    book_id bigint not null,
    author_id bigint not null,
    primary key (book_id, author_id),
    constraint fk_book_authors_book foreign key (book_id) references books(id) on delete cascade,
    constraint fk_book_authors_author foreign key (author_id) references authors(id)
);

create index idx_book_authors_author_id on book_authors(author_id);
